{{- $addon := .Values.addons.grafana }}
{{- if $addon.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $addon.names.app }}
  namespace: argocd
spec:
  destination:
    namespace: {{ $addon.namespace | default "addons-system" }}
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: {{ $addon.names.chart }}
    helm:
      valueFiles:
      - values.yaml
    repoURL: {{ $addon.repoURL}}
    targetRevision: {{ $addon.targetVersion }}
  syncPolicy:
    automated: {}
  {{- end }}